### ISSUE TITLE
open from jquery mobile popup

### ISSUE THREAD

**Issue by imryan85** [sustainablepace/mobipick#18]
mobipick does not open from text input which is located inside jquery mobile popup.

**Comment by sustainablepace** [comment]
This is beyond the scope of the plugin. Feel free to submit a pull request.

**Comment by Soulcyber** [comment]
I have the same problem... and i need to open the mobipick datepicker from it...
I'm compelled to change datepicker even if this one is really great :(
Hope to see this functionality sooner or later
