### ISSUE TITLE
Day will not go above 27th September on Mobile Safari, when on NZ time zone.

### ISSUE THREAD

**Issue by simonwatt** [sustainablepace/mobipick#23]
On mobile safari (iOS 7, tested on iPhone/iPod and iPad) the day will not go above September 27th when the year is 2014, it won't go above 26th on 2015 and so on. I haven't seen the error in Safari on pc or any other browser, including on Android devices.

I assume it is related to New Zealand daylight savings time, as my Time Zone is set to 'Auckland, New Zealand' on the device, but if I change to a different Time Zone I can no longer reproduce the error. 

Daylight Saving Time in NZ for 2014 is 28 Sep 2014, so it seems related.

This is reproducible on the demo page, on mobile safari, with Time Zone set to Auckland, New Zealand.

**Comment by sustainablepace** [comment]
This is beyond the scope of the plugin. Feel free to submit a pull request.
