### ISSUE TITLE
Is there a way to use this date picker without including the jQuery Mobile's css file?

### ISSUE THREAD

**Issue by NickSaul** [sustainablepace/mobipick#24]
I really like the functionality of this picker, but including the jQuery Mobile css file just wreaks havoc on my site. Any way to get around his?

**Comment by sustainablepace** [comment]
I'm afraid not. The datepicker was written for jQuery mobile 1.3, and has not received any updates in quite some time. It would require a major overhaul to get it to work without jQuery mobile.
